version: '2'
services:
  frontend:
    build: ./client
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/src/node_modules
    networks:
      - app-network
  backend:
    build: ./backend
    depends_on:
      - mongo
    ports:
      - '5000:5000'
    networks:
      - app-network
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network
networks:
    app-network:
        driver: bridge
volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local


